name: 'MAUIAppVersion'
description: 'Bump ApplicationVersion and ApplicationDisplayVersion'
branding:
  color: 'purple'  
  icon: 'corner-left-up'  
inputs:
  csproj:
    description: 'Path to csproj file'
    required: true
  version:
    description: 'Value for ApplicationVersion property'
    required: false
    default: '1'
  displayVersion:
    description: 'Value for ApplicationVersion property'
    required: false
    default: '1.0'
  printFile:
    description: 'Print file content'
    required: false
    default: false

runs:
  using: 'node20'
  main: 'index.js'